# Introduction to NumPy

Package: `numpy`

## NumPy Arrays vs Python Lists

- Python lists can hold any mix of value types; NumPy arrays can only hold one type of value.
- NumPy provides the array object, which is much faster and more compact than Python lists.
- A NumPy array object is called an `ndarray`: an "n-dimensional array".

## Importing NumPy

In [1]:
import numpy as np

## Creating a 1-D Array

In [2]:
one_d_array = np.array([10, 12])
print(one_d_array)

[10 12]


## Creating a New ndarray

1. `np.array()` — takes a list of values.
2. `np.arange(start, stop, step)` — returns an array of evenly spaced elements within a given interval (`start` defaults to 0 if only `stop` is given).
3. `np.linspace(start, stop, num=50)` — returns `num` evenly spaced samples over the interval `[start, stop]`. Default dtype is `float64`.
4. `np.zeros()` — returns an array with all values set to zero.
5. `np.ones()` — returns an array with all values set to one.
6. `np.empty()` — returns an array with uninitialized values; use only when you're about to overwrite them immediately.
7. `np.random.rand()` — returns an array with values chosen at random.

**Note:** `<U23` means a 23-character unicode string; `<` denotes little-endian byte order.
More on data types: https://numpy.org/doc/stable/user/basics.types.html

In [3]:
basic_arr = np.array([2, 3, 4])
print(basic_arr)

[2 3 4]


In [4]:
evenly_spaced_array = np.arange(4, 90, 8)
print(evenly_spaced_array)

[ 4 12 20 28 36 44 52 60 68 76 84]


In [5]:
lin_evenly_spaced_arr = np.linspace(100, 200, 2, dtype=int)
print(lin_evenly_spaced_arr)
char_arr = np.array(['welcome to math for ml!'])
print(char_arr)
print(char_arr.dtype)

[100 200]
['welcome to math for ml!']
<U23


In [6]:
zeros_arr = np.zeros(20)
print(zeros_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
ones_arr = np.ones(2, dtype=int)
print(ones_arr)

[1 1]


In [8]:
empty_arr = np.empty(5)
print(empty_arr)

[ 1.    2.75  6.   10.75 17.  ]


In [9]:
random_arr = np.random.rand(100)
print(random_arr)

[0.56928862 0.19813698 0.04030331 0.78844737 0.8256485  0.16442196
 0.85317346 0.08624857 0.21296751 0.87132458 0.59043648 0.93500371
 0.01899691 0.61830751 0.49697764 0.89539003 0.66505811 0.05448097
 0.42253318 0.58604568 0.00412874 0.59923132 0.66916644 0.96584072
 0.05209688 0.49115891 0.17279835 0.0857217  0.23749656 0.7373759
 0.11273233 0.42622511 0.04972969 0.13005449 0.39785145 0.17709785
 0.19334353 0.57671364 0.92675836 0.91773378 0.03608365 0.0377009
 0.73019351 0.77733113 0.08580893 0.40670735 0.43399168 0.0520142
 0.86354272 0.15756877 0.82408619 0.459297   0.15991624 0.11542725
 0.44439057 0.24241234 0.7952213  0.29253563 0.25180875 0.85158535
 0.7417721  0.32835918 0.02066564 0.64157825 0.50023667 0.547768
 0.43205004 0.68931397 0.44307577 0.10470301 0.06089584 0.04099518
 0.79805816 0.58157432 0.47314566 0.62535491 0.14067188 0.22416058
 0.21518052 0.25640787 0.38375108 0.13150691 0.12967513 0.14809942
 0.24975837 0.39826927 0.73487526 0.19848484 0.96814286 0.75784861


## Multi-Dimensional Arrays

- Create with `np.array()` on a list of lists, e.g. `np.array([[1,2,3], [4,5,6]])`.
- Reshape with `np.reshape()` — takes a 1-D array and reshapes it into the specified dimensions `(rows, cols)`.

### Finding Size, Shape, and Dimension

- `ndim` — number of dimensions of the array.
- `shape` — shape of the array; each number in the tuple is the length of the corresponding dimension.
- `size` — total number of elements in the array.

### Math Operations

- `+`, `-`, `*` work element-wise when arrays are the same size.
- **Broadcasting** lets you operate on arrays of different shapes, e.g. multiplying a vector by a scalar.

In [10]:
two_d_array = np.array([[1,2,3], [2,3,4]])
print(two_d_array)
reshaped = np.reshape(two_d_array, (1,6))
print(reshaped)

[[1 2 3]
 [2 3 4]]
[[1 2 3 2 3 4]]


In [11]:
one_dim_array = np.array([1,2,3,4,5,6])
reshaped_arr = np.reshape(one_dim_array, (2,3))
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [12]:
print(reshaped_arr.ndim)
print(reshaped_arr.size)
print(reshaped_arr.shape)

2
6
(2, 3)


In [13]:
arr_1 = np.array([5, 6, 7])
arr_2 = np.array([1, 2, 3])
print(arr_1 - arr_2)
print(arr_1 + arr_2)
print(arr_1 * arr_2)
print(arr_1 / arr_2)

[4 4 4]
[ 6  8 10]
[ 5 12 21]
[5.         3.         2.33333333]


In [14]:
vector = np.array([1, 2, 43])
print(vector * 1.6)
print(vector - 1.6)
print(vector + 1.6)
print(vector / 1.6)


[ 1.6  3.2 68.8]
[-0.6  0.4 41.4]
[ 2.6  3.6 44.6]
[ 0.625  1.25  26.875]


## Indexing and Slicing

### Indexing

- `arr[element/row]`
- `arr[row][col]`

### Slicing

- `arr[start:end:step]`
- Default `start` = 0 (inclusive)
- Default `end` = length of array
- Default `step` = 1
- Note that `a == a[:] == a[::]`

For 2-D arrays, slicing works at the row and column level — if the column isn't specified, all columns are included: `arr[1:2] == arr[1:2, :]`.

In [15]:
print(vector[2])
print(two_d_array)
print(two_d_array[0])
print(two_d_array[0][2])

43
[[1 2 3]
 [2 3 4]]
[1 2 3]
3


In [16]:
slice_arr = np.array([1, 2, 3, 4, 5])
print(slice_arr)
print(slice_arr[1:3:4])
print(slice_arr[1:])
print(slice_arr[::2])
print(two_d_array)
print(two_d_array[0:1, :])
print(two_d_array[:,:1])

[1 2 3 4 5]
[2]
[2 3 4 5]
[1 3 5]
[[1 2 3]
 [2 3 4]]
[[1 2 3]]
[[1]
 [2]]


## Stacking

Join two or more arrays along a new axis, either horizontally or vertically.

- `np.vstack()` — stacks vertically
- `np.hstack()` — stacks horizontally
- `np.hsplit()` — splits an array into several smaller arrays

**Note:** `hsplit` operates on columns (left/right pieces); `vsplit` operates on rows (top/bottom pieces).

In [17]:
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [4, 4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [18]:
vert_stack = np.vstack((a1, a2))

print(vert_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [19]:
horizontal_stack = np.hstack((a1, a2))
print(horizontal_stack)

[[1 1 3 3]
 [2 2 4 4]]


In [20]:
horizontal_split = np.hsplit(a1, 1)
print(horizontal_split)

[array([[1, 1],
       [2, 2]])]
